CREATE TABLE IF NOT EXISTS test_items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  value INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS test_tags (
  id SERIAL PRIMARY KEY,
  item_id INTEGER NOT NULL REFERENCES test_items(id),
  tag VARCHAR(255) NOT NULL
);
